version: "3.8"
services:
  redis-server:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    restart: always

  currency-app:
    build: .
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    depends_on:
      - redis-server
    ports:
      - "8080:8080"
    restart: always

